In [1]:
import os
import tensorflow as tf

# to deactivate warnings (if you didn't installed TF by source)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

print("\n\n" + "="*50)
print("Multi-variable Example")
print("="*50 + "\n\n")

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



Multi-variable Example


0 Cost:  22655.95 
Prediction:
 [[22.048063]
 [21.619785]
 [24.096693]
 [22.293016]
 [18.633898]]
100 Cost:  5.647231 
Prediction:
 [[155.50877]
 [182.1755 ]
 [182.21855]
 [194.49934]
 [141.12082]]
200 Cost:  5.4492464 
Prediction:
 [[155.43312]
 [182.2267 ]
 [182.1945 ]
 [194.48854]
 [141.18246]]
300 Cost:  5.2612314 
Prediction:
 [[155.35939]
 [182.27657]
 [182.17107]
 [194.47815]
 [141.24237]]
400 Cost:  5.0827436 
Prediction:
 [[155.28761]
 [182.32516]
 [182.14824]
 [194.46817]
 [141.30061]]
500 Cost:  4.913224 
Prediction:
 [[155.21764]
 [182.37245]
 [182.12596]
 [194.45857]
 [141.35718]]
600 Cost:  4.7521772 
Prediction:
 [[155.14946]
 [182.41852]
 [182.10422]
 [194.44937]
 [141.41216]]
700 Cost:  4.59921 
Prediction:
 [[155.08305]
 [182.46341]
 [182.08304]
 [194.44055]
 [141.46558]]
800 Cost:  4.453902 
Prediction:
 [[155.01836]
 [182.50711]
 [182.06236]
 [194.43208]
 [141.51747]]
900 Cost:  4.315795 
Prediction:
 [[154.95528]
 [182.54968]
 [182.0422 ]

In [4]:
import os
import numpy as np
import tensorflow as tf

# to deactivate warnings (if you didn't installed TF by source)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

tf.set_random_seed(777)  # for reproducibility

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]

learning_rate = 0.1

x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.nn.relu(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 10]), name='weight4')
b4 = tf.Variable(tf.random_normal([10]), name='bias4')
layer4 = tf.nn.relu(tf.matmul(layer3, W4) + b4)

W5 = tf.Variable(tf.random_normal([10, 10]), name='weight5')
b5 = tf.Variable(tf.random_normal([10]), name='bias5')
layer5 = tf.nn.relu(tf.matmul(layer4, W5) + b5)

W6 = tf.Variable(tf.random_normal([10, 10]), name='weight6')
b6 = tf.Variable(tf.random_normal([10]), name='bias6')
layer6 = tf.nn.relu(tf.matmul(layer5, W6) + b6)

W7 = tf.Variable(tf.random_normal([10, 10]), name='weight7')
b7 = tf.Variable(tf.random_normal([10]), name='bias7')
layer7 = tf.nn.relu(tf.matmul(layer6, W7) + b7)

W8 = tf.Variable(tf.random_normal([10, 1]), name='weight8')
b8 = tf.Variable(tf.random_normal([1]), name='bias8')
layer8 = tf.sigmoid(tf.matmul(layer1, W8) + b8)

learning = layer8

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(learning) + (1 - Y) *
                       tf.log(1 - learning))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(learning > 0.99, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([cost, learning, train], feed_dict={X: x_data, Y: y_data}))

    # Accuracy report
    h, c, a = sess.run([learning, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\n" + "Hypothesis: ", h, "\n" + "Correct: ", c, "\n" + "Accuracy: ", a)


0 0.6746696 [0.6746696, array([[0.7718361 ],
       [0.5394135 ],
       [0.7307448 ],
       [0.25175416]], dtype=float32), None]
1000 0.007546288 [0.007546288, array([[0.00627328],
       [0.9924332 ],
       [0.9929079 ],
       [0.00913718]], dtype=float32), None]
2000 0.0031693461 [0.0031693461, array([[0.0026233 ],
       [0.9969145 ],
       [0.9969752 ],
       [0.00392326]], dtype=float32), None]
3000 0.0019334643 [0.0019334643, array([[0.0016751 ],
       [0.9981542 ],
       [0.9981571 ],
       [0.00236246]], dtype=float32), None]
4000 0.0013661026 [0.0013661026, array([[0.00121227],
       [0.99870586],
       [0.99870384],
       [0.001658  ]], dtype=float32), None]
5000 0.0010454238 [0.0010454238, array([[9.4249926e-04],
       [9.9901342e-01],
       [9.9901235e-01],
       [1.2627214e-03]], dtype=float32), None]
6000 0.0008410523 [0.0008410523, array([[7.6648162e-04],
       [9.9920756e-01],
       [9.9920791e-01],
       [1.0118107e-03]], dtype=float32), None]
7000 0.